# Generated by Django 5.1.4 on 2025-04-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_members_memb_num_street_alter_members_memb_zp'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='memb_num_gsm',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
