# Generated by Django 5.1.4 on 2025-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_memb_birth_date_alter_members_memb_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='memb_num_street',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='memb_zp',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
