# Generated by Django 5.1.4 on 2025-09-30 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50, unique=True)),
                ('lang_abbr', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'ordering': ['lang_name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chld_name', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('chld_surname', models.CharField(max_length=100, null=True, verbose_name='Prénom')),
                ('chld_birthdate', models.DateField(verbose_name='Date de naissance')),
                ('chld_gender', models.CharField(choices=[('Garçon', 'Garçon'), ('Fille', 'Fille')], default='Garçon', max_length=10, verbose_name='Genre')),
                ('chld_spcl_attention', models.TextField(blank=True, null=True, verbose_name='Attention particulière')),
                ('chld_seat', models.BooleanField(default=False, verbose_name='Siège enfant nécessaire')),
                ('chld_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('ci_is_verified', models.BooleanField(default=False)),
                ('bvm_is_verified', models.BooleanField(default=False)),
                ('prfl_is_verified', models.BooleanField(default=False)),
                ('document_bvm', models.FileField(blank=True, null=True, upload_to='bvm/', verbose_name="Bonne vie et moeurs (extrait 596.2, utilisé dans le cadre de l'encadrement de mineurs)")),
                ('service', models.CharField(choices=[('Parent', 'Parent'), ('Yaya', 'Yaya')], max_length=30)),
                ('transport_modes', models.JSONField(blank=True, default=list, null=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('verified_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.ManyToManyField(blank=True, null=True, to='accounts.languages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
