# Generated by Django 5.1.6 on 2025-04-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
