# Generated by Django 5.1.4 on 2025-09-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='document_image_url',
        ),
    ]
