# Generated by Django 5.1.4 on 2025-06-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_fullname_remove_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, choices=[('french', 'French'), ('english', 'English'), ('spanish', 'Spanish'), ('arabic', 'Arabic'), ('turkish', 'Turkish'), ('italian', 'Italian'), ('other', 'Other')], default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.JSONField(blank=True, choices=[('parent', 'Parent'), ('mentor', 'Mentor')], default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='transport_modes',
            field=models.JSONField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike'), ('public_transport', 'Public Transport'), ('walking', 'Walking')], default=list),
        ),
    ]
