# Generated by Django 5.1.4 on 2025-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_image_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50, unique=True)),
                ('lang_abbr', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
