# Generated by Django 5.1.4 on 2026-03-06 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favoriteadresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('label', models.CharField(help_text='Ex: Maison, École, Sport...', max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_addresse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('user', 'label')},
            },
        ),
        migrations.DeleteModel(
            name='FavoriteAdresse',
        ),
    ]
