# Generated by Django 5.1.4 on 2025-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_document_image_url_profile_verified_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_dob',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
