# Generated by Django 5.1.4 on 2025-07-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_verified_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verified',
            new_name='ci_is_verified',
        ),
    ]
