# Generated by Django 5.1.4 on 2025-07-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_is_verified_profile_ci_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bvm_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
