# Generated by Django 5.1.4 on 2026-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_favoriteaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='chld_spcl_attention',
        ),
        migrations.AddField(
            model_name='child',
            name='chld_disability',
            field=models.BooleanField(default=False, verbose_name="Porteur d'un handicap"),
        ),
        migrations.AddField(
            model_name='child',
            name='chld_languages',
            field=models.ManyToManyField(blank=True, to='accounts.languages', verbose_name='Langue(s) parlée(s)'),
        ),
        migrations.AddField(
            model_name='child',
            name='chld_special_needs',
            field=models.TextField(blank=True, null=True, verbose_name='Besoins spécifiques'),
        ),
    ]
