# Generated by Django 5.1.4 on 2025-07-16 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chld_name', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('chld_surname', models.CharField(max_length=100, null=True, verbose_name='Prénom')),
                ('chld_birthdate', models.DateField(verbose_name='Date de naissance')),
                ('chld_gender', models.CharField(choices=[('Garçon', 'Garçon'), ('Fille', 'Fille')], default='Garçon', max_length=10, verbose_name='Genre')),
                ('chld_spcl_attention', models.TextField(blank=True, null=True, verbose_name='Attention particulière')),
                ('chld_seat', models.BooleanField(default=False, verbose_name='Siège enfant nécessaire')),
                ('chld_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
