# Generated by Django 5.1.4 on 2025-07-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_bvm_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prfl_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
