# Generated by Django 5.1.4 on 2026-03-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_child_chld_spcl_attention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='chld_languages',
            field=models.ManyToManyField(blank=True, related_name='children', to='accounts.languages', verbose_name='Langue(s) parlée(s)'),
        ),
    ]
