# Generated by Django 5.1.4 on 2025-07-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_prfl_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_bvm',
            field=models.FileField(blank=True, null=True, upload_to='bvm/', verbose_name='Bonne vie et moers'),
        ),
    ]
