# Generated by Django 5.1.4 on 2025-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service',
            field=models.CharField(max_length=30),
        ),
    ]
