# Generated by Django 5.1.4 on 2026-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_child_chld_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_seen',
            field=models.BooleanField(default=False),
        ),
    ]
