# Generated by Django 5.1.4 on 2025-07-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service',
            field=models.CharField(choices=[('parent', 'Parent'), ('yaya', 'Yaya')], max_length=30),
        ),
    ]
