# Generated by Django 5.1.4 on 2025-07-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bvm_is_verified_profile_ci_is_verified_and_more'),
        ('accounts', '0008_profile_document_bvm'),
    ]

    operations = [
    ]
