# Generated by Django 5.1.4 on 2025-09-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250731_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified_dob',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document_bvm',
            field=models.FileField(blank=True, null=True, upload_to='bvm/', verbose_name="Bonne vie et moeurs (extrait 596.2, utilisé dans le cadre de l'encadrement de mineurs)"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.languages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Yaya', 'Yaya')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='transport_modes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
