# Generated by Django 5.1.4 on 2025-09-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250731_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_bvm',
            field=models.FileField(blank=True, null=True, upload_to='bvm/', verbose_name="Bonne vie et moeurs (extrait 596.2, utilisé dans le cadre de l'encadrement de mineurs)"),
        ),
    ]
