# Generated by Django 5.1.4 on 2025-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_document_bvm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.languages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='transport_modes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
