# Generated by Django 5.2.16 on 2026-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_prefix',
            field=models.CharField(blank=True, default='+32', max_length=5),
        ),
    ]
