# Generated by Django 5.2.16 on 2026-09-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_phone_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_etablissement', models.PositiveIntegerField()),
                ('fase_implantation', models.PositiveIntegerField()),
                ('numero_bce', models.CharField(blank=True, max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('reseau', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('commune', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('fase_etablissement', 'fase_implantation')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.ecole'),
        ),
    ]
