# Generated by Django 5.1.4 on 2025-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_phone_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified_dob',
        ),
        migrations.AlterField(
            model_name='profile',
            name='service',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Yaya', 'Yaya')], max_length=30),
        ),
    ]
