# Generated by Django 5.1.4 on 2025-09-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_login_completed',
            field=models.BooleanField(default=False),
        ),
    ]
