# Generated by Django 5.1.4 on 2025-09-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_account_activated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_activated_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_login_completed',
        ),
    ]
