# Generated by Django 5.1.4 on 2025-10-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bana_admin', '0002_sitevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='path',
        ),
    ]
