# Generated by Django 5.1.4 on 2025-10-21 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bana_admin', '0003_remove_sitevisit_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='sitevisit',
            unique_together={('ip_address', 'user')},
        ),
    ]
