# Generated by Django 5.1.4 on 2025-10-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bana_admin', '0005_activeuser_dailystats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyStats',
        ),
        migrations.DeleteModel(
            name='ActiveUser',
        ),
    ]
