# Generated by Django 5.1.4 on 2025-07-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='reproduction_steps',
            field=models.TextField(blank=True, null=True, verbose_name='Étapes de reproduction'),
        ),
    ]
