# Generated by Django 5.1.4 on 2025-09-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0002_alter_bug_reproduction_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='browser',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='device',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Appareil'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='operating_system',
            field=models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name="Système d'exploitation"),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reproduction_steps',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Étapes de reproduction'),
        ),
    ]
