"""
Django settings for bana project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from decouple import config
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*umwdzm=4)s(*x)hq1_)yd(6mtbrwy5gh8%b^_d(kn8xnspgc('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '37.187.94.53']

print("37.187.94.53:8800")

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'channels',
    
     #Authentification
    'accounts',
    'allauth',
    'allauth.account',
    'allauth.socialaccount', # Pour la connection via les reseaux-sociaux
    'allauth.socialaccount.providers.google', # Pour la connection via google
    
    # my extensions
    'django_extensions',
    'tailwind',    
    'theme',
    'crispy_forms',
    'crispy_bootstrap4',
    'django_htmx',

    # my apps 
    'bana',
    'bana_admin',
    'bug_tracker',
    'chat',
    'stripe_sub',
    'trajects.apps.TrajectsConfig',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

SITE_ID = 1

ROOT_URLCONF = 'bana.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bana.wsgi.application'

# Chemin vers l'application ASGI
ASGI_APPLICATION = 'bana.asgi.application'
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""
ICI COMMENCE L'AJOUT DE CODE POUR LE BUG TRACKER
"""
# Configuration de l'upload de fichiers
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10MB

# Types de fichiers autorisés pour les pièces jointes
ALLOWED_ATTACHMENT_TYPES = [
    'image/jpeg', 'image/png', 'image/gif',
    'application/pdf', 'text/plain', 'text/csv',
    'application/zip', 'application/x-zip-compressed',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
]


# Taille maximale des pièces jointes (5MB)
MAX_ATTACHMENT_SIZE = 5 * 1024 * 1024

# Configuration de pagination
BUGS_PER_PAGE = 20

# Configuration des emails (optionnel pour les notifications)
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Pour développement
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Pour production
#EMAIL_HOST = 'localhost'
#EMAIL_PORT = 1025
#EMAIL_USE_TLS = False
#DEFAULT_FROM_EMAIL = 'bugtracker@example.com'

# Configuration HTMX
HTMX_REQUIRE_CSRF = True

# Configuration des logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'bug_tracker.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'bug_tracker': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
    }

"""
ICI TERMINE L'AJOUT DE CODE POUR LE BUG TRACKER
"""



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
USE_I18N = True
# Configuration de la timezone
TIME_ZONE = 'UTC'
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'bana/static' ]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# tailwinds & Crispy 

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# API key 

OPEN_STREET_MAP_API_KEY = config("OPEN_STREET_MAP_API", default="default_value")

GOOGLE_MAPS_API_KEY = config("GOOGLE_MAPS_API_KEY",default="default_value")

#Authentication backends

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE' : [
            'profile',
            'email'
        ],
        
        'AUTH_PARAMS': {
            'prompt': 'select_account'
        }
    }
}

# URL for login redirect 
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/' 

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# 🧠 Email verification obligatoire
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # auto-confirmation au clic
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/accounts/profile/" 

# 🔒 Empêche que des bots puissent détecter les emails existants
ACCOUNT_PREVENT_ENUMERATION = False  # sécurité activée

# 🔐 Envoie un vrai lien sécurisé (sans stocker de clé en DB)
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True



ACCOUNT_INACTIVE_USER_ERROR = "Ce compte est désactivé. Contacte un admin pour le réactiver."


# A compléter
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'hellobanacommunity@gmail.com'  # Votre adresse email
#EMAIL_HOST_PASSWORD = 'your-email-password'  # Votre mot de passe d'email
#DEFAULT_FROM_EMAIL = 'your-email@gmail.com'  # Adresse par défaut pour l'expéditeur

# Configurer l'email
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # Remplace par ton serveur SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'Lucacamilleri55@gmail.com'
EMAIL_HOST_PASSWORD = 'bqyu cpzk looj hydh' 
DEFAULT_FROM_EMAIL = "Lucacamilleri55@gmail.com"

ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm'
}

STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY_TEST",default="secret")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY_TEST",default="secret")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET_TEST",default="secret")

