# Generated by Django 5.1.4 on 2025-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0002_proposedtraject_date_researchedtraject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='traject',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
