# Generated by Django 5.1.4 on 2025-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0005_alter_reservation_traject'),
    ]

    operations = [
        migrations.AddField(
            model_name='traject',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='recurrence_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='recurrence_interval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Toutes les semaines'), ('weekly_interval', 'Toutes les x semaines'), ('specific_days', 'Jours spécifiques')], max_length=50, null=True),
        ),
    ]
