# Generated by Django 5.1.4 on 2025-07-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0007_alter_members_memb_num_gsm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_adress', models.CharField(max_length=255)),
                ('end_adress', models.CharField(max_length=255)),
                ('start_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_street', models.CharField(blank=True, max_length=100, null=True)),
                ('start_number', models.CharField(blank=True, max_length=10, null=True)),
                ('start_box', models.CharField(blank=True, max_length=10, null=True)),
                ('start_zp', models.CharField(blank=True, max_length=10, null=True)),
                ('start_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('start_region', models.CharField(blank=True, max_length=100, null=True)),
                ('start_commune', models.CharField(blank=True, max_length=100, null=True)),
                ('start_country', models.CharField(blank=True, default='Belgium', max_length=100, null=True)),
                ('start_coordinate', models.CharField(blank=True, max_length=50, null=True)),
                ('end_name', models.CharField(blank=True, max_length=100, null=True)),
                ('end_street', models.CharField(blank=True, max_length=100, null=True)),
                ('end_number', models.CharField(blank=True, max_length=10, null=True)),
                ('end_box', models.CharField(blank=True, max_length=10, null=True)),
                ('end_zp', models.CharField(blank=True, max_length=10, null=True)),
                ('end_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('end_region', models.CharField(blank=True, max_length=100, null=True)),
                ('end_commune', models.CharField(blank=True, max_length=100, null=True)),
                ('end_country', models.CharField(blank=True, default='Belgium', max_length=100)),
                ('end_coordinate', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposedTraject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('date', models.DateField()),
                ('number_of_places', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1)),
                ('details', models.TextField()),
                ('detour_distance', models.FloatField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('recurrence_type', models.CharField(blank=True, choices=[('none', 'None'), ('weekly', 'Toutes les semaines'), ('weekly_interval', 'Toutes les x semaines'), ('specific_days', 'Jours spécifiques')], max_length=50, null=True)),
                ('recurrence_interval', models.IntegerField(blank=True, default=1, null=True)),
                ('recurrence_days', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_trajects', to=settings.AUTH_USER_MODEL)),
                ('traject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajects.traject')),
                ('transport_modes', models.ManyToManyField(related_name='proposed_trajects', to='trajects.transportmode')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_places', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members', verbose_name='User who made the reservation')),
                ('traject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trajects.proposedtraject')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchedTraject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('date', models.DateField()),
                ('number_of_places', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1)),
                ('details', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researched_trajects', to='members.members')),
                ('traject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajects.traject')),
                ('transport_modes', models.ManyToManyField(related_name='researched_trajects', to='trajects.transportmode')),
            ],
        ),
    ]
