# Generated by Django 5.1.3 on 2024-12-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(blank=True, max_length=100)),
                ('start_street', models.CharField(blank=True, max_length=100)),
                ('start_number', models.CharField(blank=True, max_length=10)),
                ('start_box', models.CharField(blank=True, max_length=10)),
                ('start_zp', models.CharField(blank=True, max_length=10)),
                ('start_locality', models.CharField(blank=True, max_length=100)),
                ('start_country', models.CharField(default='Belgium', max_length=100)),
                ('end_location', models.CharField(blank=True, max_length=100)),
                ('end_street', models.CharField(blank=True, max_length=100)),
                ('end_number', models.CharField(blank=True, max_length=10)),
                ('end_box', models.CharField(blank=True, max_length=10)),
                ('end_zp', models.CharField(blank=True, max_length=10)),
                ('end_locality', models.CharField(blank=True, max_length=100)),
                ('end_country', models.CharField(default='Belgium', max_length=100)),
                ('start_coordinate', models.CharField(blank=True, max_length=50, null=True)),
                ('end_coordinate', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchedTraject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('member', models.ManyToManyField(related_name='researched_trajects', to='members.members')),
                ('traject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajects.traject')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedTraject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('member', models.ManyToManyField(related_name='proposed_trajects', to='members.members')),
                ('traject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajects.traject')),
            ],
        ),
    ]
