# Generated by Django 5.1.4 on 2025-07-09 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_phone'),
        ('trajects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchedtraject',
            name='member',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='end_box',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='end_commune',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='end_name',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='end_number',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='end_region',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='end_zp',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='start_box',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='start_commune',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='start_name',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='start_number',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='start_region',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='start_zp',
        ),
        migrations.AddField(
            model_name='proposedtraject',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='proposed_trajects', to='accounts.languages'),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='researched_trajects', to='accounts.languages'),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researched_trajects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traject',
            name='end_cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal arrivée'),
        ),
        migrations.AddField(
            model_name='traject',
            name='start_cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal départ'),
        ),
        migrations.AlterField(
            model_name='proposedtraject',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('weekly', 'Chaque semaine'), ('weekly_interval', 'Toutes les x semaines'), ('specific_days', 'Jours spécifiques')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_adress',
            field=models.CharField(max_length=255, verbose_name='Adresse d’arrivée (libre)'),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_coordinate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordonnées arrivée'),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_locality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ville d'arrivée"),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rue d’arrivée'),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_adress',
            field=models.CharField(max_length=255, verbose_name='Adresse de départ (libre)'),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_coordinate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordonnées départ'),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_locality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville de départ'),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rue de départ'),
        ),
    ]
