# Generated by Django 5.1.4 on 2025-07-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='transport_modes',
            field=models.ManyToManyField(blank=True, related_name='proposed_trajects', to='trajects.transportmode'),
        ),
        migrations.AlterField(
            model_name='researchedtraject',
            name='transport_modes',
            field=models.ManyToManyField(blank=True, related_name='researched_trajects', to='trajects.transportmode'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='transport_modes',
            field=models.ManyToManyField(blank=True, to='trajects.transportmode'),
        ),
    ]
