# Generated by Django 5.1.4 on 2025-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traject',
            name='end_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='traject',
            name='start_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
