# Generated by Django 5.1.4 on 2025-02-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0002_proposedtraject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='date',
            field=models.DateField(),
        ),
    ]
