# Generated by Django 5.1.4 on 2025-07-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0002_remove_researchedtraject_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposedtraject',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='researchedtraject',
            old_name='language',
            new_name='languages',
        ),
    ]
