# Generated by Django 5.1.4 on 2025-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0002_traject_end_name_traject_start_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtraject',
            name='number_of_place',
            field=models.SmallIntegerField(default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='number_of_place',
            field=models.SmallIntegerField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
