# Generated by Django 5.1.4 on 2025-10-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0002_alter_reservation_traject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='traject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajects.proposedtraject'),
        ),
    ]
