# Generated by Django 5.1.4 on 2025-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0002_alter_proposedtraject_transport_modes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='number_of_places',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default=1, null=True),
        ),
    ]
