# Generated by Django 5.1.4 on 2025-07-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0003_alter_proposedtraject_number_of_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='number_of_places',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], null=True),
        ),
    ]
