# Generated by Django 5.1.4 on 2025-02-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0003_alter_proposedtraject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchedtraject',
            name='date',
            field=models.DateField(default='2025-02-13'),
            preserve_default=False,
        ),
    ]
