# Generated by Django 5.1.4 on 2025-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0003_rename_language_proposedtraject_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traject',
            name='date',
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='recurrence_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='recurrence_interval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('weekly', 'Chaque semaine'), ('weekly_interval', 'Toutes les x semaines'), ('specific_days', 'Jours spécifiques')], max_length=50, null=True),
        ),
    ]
