# Generated by Django 5.1.4 on 2025-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0004_alter_proposedtraject_number_of_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traject',
            name='end_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
