# Generated by Django 5.1.4 on 2025-07-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0004_remove_traject_date_researchedtraject_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposedtraject',
            name='recurrence_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposedtraject',
            name='recurrence_type',
            field=models.CharField(choices=[('none', '1x par semaine'), ('weekly', 'Chaque semaine'), ('biweekly', 'Une semaine sur deux')], default='none', max_length=30),
        ),
    ]
