# Generated by Django 5.1.4 on 2025-07-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0004_alter_proposedtraject_number_of_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='number_of_places',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
