# Generated by Django 5.1.4 on 2025-08-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0005_alter_proposedtraject_number_of_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtraject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
