# Generated by Django 5.1.4 on 2025-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0005_alter_proposedtraject_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='recurrence_type',
            field=models.CharField(choices=[('one_week', 'Une semaine seulement'), ('weekly', 'Chaque semaine'), ('biweekly', 'Une semaine sur deux')], default='none', max_length=30),
        ),
    ]
