# Generated by Django 5.1.4 on 2025-10-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0005_fill_proposed_researched'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='proposed_traject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trajects.proposedtraject'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='researched_traject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trajects.researchedtraject'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='traject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajects.traject'),
        ),
    ]
