# Generated by Django 5.1.4 on 2025-01-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0005_alter_traject_end_name_alter_traject_start_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposedtraject',
            old_name='number_of_place',
            new_name='number_of_places',
        ),
        migrations.RenameField(
            model_name='researchedtraject',
            old_name='number_of_place',
            new_name='number_of_places',
        ),
        migrations.RemoveField(
            model_name='proposedtraject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='researchedtraject',
            name='name',
        ),
        migrations.AddField(
            model_name='proposedtraject',
            name='language',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='language',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
