# Generated by Django 5.1.4 on 2025-10-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0006_reservation_proposed_traject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='traject',
        ),
    ]
