# Generated by Django 5.1.4 on 2025-01-20 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0006_rename_number_of_place_proposedtraject_number_of_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traject',
            name='end_adress',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traject',
            name='start_adress',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_box',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_country',
            field=models.CharField(blank=True, default='Belgium', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_zp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_box',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_country',
            field=models.CharField(blank=True, default='Belgium', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='start_zp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
