# Generated by Django 5.1.4 on 2025-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0006_alter_proposedtraject_recurrence_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchedtraject',
            name='languages',
        ),
        migrations.AlterField(
            model_name='researchedtraject',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchedtraject',
            name='recurrence_type',
            field=models.CharField(choices=[('one_week', 'Une semaine seulement'), ('weekly', 'Chaque semaine'), ('biweekly', 'Une semaine sur deux')], default='none', max_length=30),
        ),
    ]
