# Generated by Django 5.1.4 on 2025-01-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0007_traject_end_adress_traject_start_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposedtraject',
            name='language',
        ),
        migrations.RemoveField(
            model_name='researchedtraject',
            name='language',
        ),
        migrations.AlterField(
            model_name='researchedtraject',
            name='number_of_places',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1),
        ),
    ]
