# Generated by Django 5.1.4 on 2025-03-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0007_remove_traject_date_debut_remove_traject_date_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchedtraject',
            name='language',
        ),
        migrations.RemoveField(
            model_name='proposedtraject',
            name='language',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
