# Generated by Django 5.1.4 on 2025-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_phone'),
        ('trajects', '0007_remove_researchedtraject_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchedtraject',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='researched_trajects', to='accounts.languages'),
        ),
    ]
