# Generated by Django 5.1.4 on 2025-10-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0007_remove_reservation_traject'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtraject',
            name='search_radius_km',
            field=models.IntegerField(default=5, help_text='Rayon en kilomètres pour les trajets simples (5 km par défaut)', verbose_name='Rayon de recherche (km)'),
        ),
    ]
