# Generated by Django 5.1.4 on 2025-03-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0008_remove_researchedtraject_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traject',
            name='end_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='start_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
