# Generated by Django 5.1.4 on 2025-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_phone'),
        ('trajects', '0008_researchedtraject_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchedtraject',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchedtraject',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='researched_trajects', to='accounts.languages'),
        ),
        migrations.AlterField(
            model_name='researchedtraject',
            name='number_of_places',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='researchedtraject',
            name='recurrence_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
