# Generated by Django 5.1.4 on 2025-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0008_proposedtraject_search_radius_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='search_radius_km',
            field=models.IntegerField(blank=True, default=5, help_text='Rayon en kilomètres pour les trajets simples (5 km par défaut)', null=True, verbose_name='Rayon de recherche (km)'),
        ),
    ]
