# Generated by Django 5.1.4 on 2025-01-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0008_languages_remove_proposedtraject_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtraject',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trajects.languages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trajects.languages'),
            preserve_default=False,
        ),
    ]
