# Generated by Django 5.1.4 on 2025-07-16 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0009_alter_researchedtraject_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedTraject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('recurrence_type', models.CharField(choices=[('one_week', 'Une semaine seulement'), ('weekly', 'Chaque semaine'), ('biweekly', 'Une semaine sur deux')], default='none', max_length=30)),
                ('recurrence_interval', models.IntegerField(blank=True, null=True)),
                ('recurrence_days', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('traject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajects.traject')),
                ('transport_modes', models.ManyToManyField(related_name='searched_trajects', to='trajects.transportmode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searched_trajects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
