# Generated by Django 5.1.4 on 2025-10-30 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0009_alter_proposedtraject_search_radius_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtraject',
            name='confirmed_users',
            field=models.ManyToManyField(blank=True, help_text='Liste des utilisateurs ayant une réservation confirmée pour ce trajet.', related_name='confirmed_proposed_trajets', to=settings.AUTH_USER_MODEL),
        ),
    ]
