# Generated by Django 5.1.4 on 2025-03-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0009_traject_end_postal_code_traject_start_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traject',
            name='end_postal_code',
        ),
        migrations.RemoveField(
            model_name='traject',
            name='start_postal_code',
        ),
    ]
