# Generated by Django 5.1.4 on 2025-07-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0010_searchedtraject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchedTraject',
        ),
    ]
