# Generated by Django 5.1.4 on 2025-03-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0010_remove_traject_end_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('weekly', 'Toutes les semaines'), ('weekly_interval', 'Toutes les x semaines'), ('specific_days', 'Jours spécifiques')], max_length=50, null=True),
        ),
    ]
