# Generated by Django 5.1.4 on 2025-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0011_alter_proposedtraject_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchedtraject',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='researched_trajects', to='trajects.languages'),
        ),
    ]
