# Generated by Django 5.1.4 on 2025-07-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0011_delete_searchedtraject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchedtraject',
            name='details',
        ),
        migrations.RemoveField(
            model_name='researchedtraject',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='researchedtraject',
            name='number_of_places',
        ),
    ]
