# Generated by Django 5.1.4 on 2025-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_child'),
        ('trajects', '0012_remove_researchedtraject_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='details',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposedtraject',
            name='languages',
            field=models.ManyToManyField(related_name='proposed_trajects', to='accounts.languages'),
        ),
        migrations.AlterField(
            model_name='researchedtraject',
            name='transport_modes',
            field=models.ManyToManyField(blank=True, null=True, related_name='researched_trajects', to='trajects.transportmode'),
        ),
    ]
