# Generated by Django 5.1.4 on 2026-02-23 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0012_remove_proposedtraject_groupes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchedtraject',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='proposedtraject',
            name='groupe',
        ),
        migrations.AddField(
            model_name='proposedtraject',
            name='groupe_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='proposedtraject',
            name='groupe_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='groupe_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='researchedtraject',
            name='groupe_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='TrajectGroupe',
        ),
    ]
