# Generated by Django 5.1.4 on 2025-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0012_alter_researchedtraject_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='traject',
            name='end_commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='end_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='start_commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='start_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
