# Generated by Django 5.1.4 on 2026-03-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0013_remove_researchedtraject_groupe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traject',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='traject',
            name='address',
        ),
    ]
