# Generated by Django 5.1.4 on 2025-07-22 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0013_alter_proposedtraject_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant réservé'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_places',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('canceled', 'Annulée')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='traject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajects.proposedtraject'),
        ),
    ]
