# Generated by Django 5.1.4 on 2026-03-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0014_alter_traject_options_remove_traject_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='traject',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='end_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traject',
            name='start_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
