# Generated by Django 5.1.4 on 2026-04-02 09:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0015_traject_address_traject_end_place_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trajet', 'verbose_name_plural': 'Trajets'},
        ),
        migrations.RemoveField(
            model_name='traject',
            name='is_test',
        ),
        migrations.AlterField(
            model_name='traject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='traject',
            name='end_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Coordonnée d’arrivée'),
        ),
    ]
