# Generated by Django 5.1.4 on 2025-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0015_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtraject',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposedtraject',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposedtraject',
            name='number_of_places',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1, null=True),
        ),
    ]
