# Generated by Django 5.1.4 on 2025-07-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0016_alter_proposedtraject_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtraject',
            name='is_simple',
            field=models.BooleanField(default=False),
        ),
    ]
