# Generated by Django 5.2.16 on 2026-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0016_alter_traject_options_remove_traject_is_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='canceled_by',
            field=models.CharField(blank=True, choices=[('parent', 'Annulée par le parent'), ('yaya', 'Refusée par le conducteur'), ('auto', 'Annulée automatiquement')], max_length=10, null=True),
        ),
    ]
