# Generated by Django 5.1.4 on 2025-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_sub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
