# Generated by Django 5.1.4 on 2025-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_sub', '0002_subscription_price_subscription_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='product_name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='service_type',
            field=models.CharField(blank=True, choices=[('yaya', 'Yaya'), ('parent', 'Parent')], max_length=10, null=True),
        ),
    ]
