# Generated by Django 5.1.4 on 2025-07-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_sub', '0003_remove_subscription_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='service_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
