# Generated by Django 5.1.4 on 2025-04-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='memb_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='memb_box',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='memb_gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme'), ('X', 'Non Genré')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='memb_locality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='memb_num_street',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='memb_street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='memb_zp',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
