# Generated by Django 5.1.4 on 2025-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_members_memb_num_gsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='memb_num_gsm',
            field=models.SmallIntegerField(),
        ),
    ]
